/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Proyecto_DLL */

#ifndef _Included_Proyecto_DLL
#define _Included_Proyecto_DLL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Proyecto_DLL
 * Method:    limpiar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Proyecto_1DLL_limpiar
  (JNIEnv *, jobject);

/*
 * Class:     Proyecto_DLL
 * Method:    titulo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Proyecto_1DLL_titulo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Proyecto_DLL
 * Method:    posicion
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Proyecto_1DLL_posicion
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Proyecto_DLL
 * Method:    cambiarColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Proyecto_1DLL_cambiarColor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
