/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego Mendez
 */
public class VentasCelular extends javax.swing.JFrame {
    DefaultTableModel modelo;
    int utilidades[];
    /**
     * Creates new form VentasCelular
     */
    public VentasCelular() {
        super("Venta de Celulares");
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        modelo=(DefaultTableModel) jTable1.getModel();
   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxlanzar = new javax.swing.JTextField();
        jtxadqui = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnborrar = new javax.swing.JButton();
        adad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbmoda = new javax.swing.JLabel();
        jlbdesv = new javax.swing.JLabel();
        jlbmedia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de simulaciones");

        jLabel2.setText("Celulares Adquridos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "#aleatorio", "Cel Vendidos", "Cel Devueltos", "Costo", "Ingre x dev", "Ingre x Vender", "Utilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        adad.setText("Moda:");

        jLabel4.setText("Desv.Estandar:");

        jLabel5.setText("Media:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxlanzar))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxadqui))
                        .addGap(69, 69, 69)
                        .addComponent(btnaceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnborrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(adad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbmoda)
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbdesv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbmedia)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxlanzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxadqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnaceptar)
                        .addComponent(btnborrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adad)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jlbmoda)
                    .addComponent(jlbdesv)
                    .addComponent(jlbmedia))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        
        Random rn = new Random();
        int n=0;
        int adquiridos=0;
        int devueltos=0;
        int costo=0;
        int ingxdev=0;
        int ingxvent=0;
        int utilidad=0;
        
        try {
            n=Integer.parseInt(jtxlanzar.getText());
            adquiridos=Integer.parseInt(jtxadqui.getText());
        } catch (Exception e) {
        }
          
         Object [] fila=new Object[8]; 
         utilidades=new int[n];
         int x=0;
        for (int i = 1; i <=n; i++) {
            double y=rn.nextDouble();
            int celvend=0;
            
            fila[0]=i;
            fila[1]=y;
            if (y>=0&&y<=0.30) {
              celvend=100;
              if(adquiridos>celvend)
              {
                 devueltos=Math.abs(adquiridos-celvend);
              }
              if(adquiridos<celvend)
              {
                 celvend=adquiridos;
                 devueltos=0;
              }
              fila[2]=celvend;
              fila[3]=devueltos;
            }else
                if (y>=0.31&&y<=0.50) {
                 celvend=150;
                 if(adquiridos>celvend)
                {
                 devueltos=Math.abs(adquiridos-celvend);
                }
                if(adquiridos<celvend)
                 {
                 celvend=adquiridos;
                 devueltos=0;
                 }
                 fila[2]=celvend;     
                 fila[3]=devueltos;
            }else
                    if (y>=0.51&&y<=0.80) {
                        celvend=200;
                         if(adquiridos>celvend)
                        {
                           devueltos=Math.abs(adquiridos-celvend);
                        }
                        if(adquiridos<celvend)
                         {
                         celvend=adquiridos;
                         devueltos=0;
                         }
                        fila[2]=celvend;
                        fila[3]=devueltos;
            }else
                        if (y>=0.81&&y<=0.95) {
                          celvend=250;
                           if(adquiridos>celvend)
                            {
                               devueltos=Math.abs(adquiridos-celvend);
                            }
                            if(adquiridos<celvend)
                             {
                             celvend=adquiridos;
                             devueltos=0;
                             }
                          fila[2]=celvend;
                          fila[3]=devueltos;
            }else
                            if (y>=0.96&&y<=1) {
                          celvend=300;
                           if(adquiridos>celvend)
                            {
                                devueltos=Math.abs(adquiridos-celvend);
                            }
                            if(adquiridos<celvend)
                             {
                             celvend=adquiridos;
                             devueltos=0;
                             }
                          fila[2]=celvend;
                          fila[3]=devueltos;
            }
            costo=adquiridos*75;
            fila[4]=costo;
            ingxdev=devueltos*25;
            fila[5]=ingxdev;
            ingxvent=celvend*100;
            fila[6]=ingxvent;
            utilidad=ingxvent+ingxdev-costo;
            fila[7]=utilidad;
            utilidades[x]=utilidad;
            x++;
            modelo.addRow(fila);
            
            
           
            
            
        }
                
                //media    
                double suma= 0;
                double media=0;
                for(int j=0; j<=n-1; j++) {
                    
                suma=suma+utilidades[j];
                   
                    

                }
                media=suma/n;
                System.out.println(suma);
                jlbmedia.setText(String.valueOf(media));
                
                //moda
                int moda=0,frec=0;
                for(int k=0;k<n-1;k++)
                if(utilidades[k]>frec)
                {
                    frec=utilidades[k];
                    moda=utilidades[k];
                }
                jlbmoda.setText(String.valueOf(moda));
                
                //desv.estandar
                double varianza=0;
                double desviacion=0;
                for(int l = 0 ; l < n-1; l++){
                 double rango;
                 rango = Math.pow(utilidades[l] - media, 2);
                 varianza = varianza + rango;
                 }
                varianza = varianza /n;
                 desviacion = Math.sqrt(varianza);
                 jlbdesv.setText(String.valueOf(desviacion));
        
        
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        jtxadqui.setText("");
        jtxlanzar.setText("");
        jlbdesv.setText("");
        jlbmedia.setText("");
        jlbmoda.setText("");
        Clear_Table1();
    }//GEN-LAST:event_btnborrarActionPerformed
    
    private void Clear_Table1(){
        for (int i = 0; i < jTable1.getRowCount(); i++) {
        modelo.removeRow(i);
        i-=1;
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasCelular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adad;
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbdesv;
    private javax.swing.JLabel jlbmedia;
    private javax.swing.JLabel jlbmoda;
    private javax.swing.JTextField jtxadqui;
    private javax.swing.JTextField jtxlanzar;
    // End of variables declaration//GEN-END:variables
}
